apiVersion: v1
kind: ConfigMap
metadata:
  name: grabshow-config
  namespace: default
data:
  # MySQL Configuration
  MYSQL_USER: "bookmyshow"
  
  # JPA/Hibernate Configuration
  JPA_DDL_AUTO: "update"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  
  # Spring Boot Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics"
