---
apiVersion: v1
kind: Service
metadata:
  name: user-service-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30001
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: event-service-np
  namespace: default
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: event-service
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30002
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: booking-service
  ports:
  - port: 8003
    targetPort: 8003
    nodePort: 30003
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: cart-service
  ports:
  - port: 8004
    targetPort: 8004
    nodePort: 30004
    protocol: TCP
